on: push

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: gamekiller2048/Godot-Unsigned-IOS@v2
        with:
          # The version of Godot downloaded.
          godot-version: "4.7.1"

          # The flavor of Godot downloaded.
          godot-flavor: "stable"

          # The name of the Xcode project and generated IPA.
          export-name: "my-ios-project"

          # The configuration of both the godot export and xcode build. Can be release|debug.
          configuration: "release"